
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
# DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

#INCLUDE_LOCATIONS += /usr/local/opt/llvm/include
#LIBRARY_LOCATIONS += /usr/local/opt/llvm/lib
#LIBRARIES += -lomp

USE_MPI    = TRUE
# USE_OMP    = FALSE
# USE_OMP    = TRUE 
USE_CUDA   = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include Make.Adv
